# FROM nvidia/cudagl:11.3.0-devel-ubuntu20.04
FROM nvcr.io/nvidia/pytorch:25.06-py3-igpu

ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# RUN apt-get update --fix-missing && \
#     apt-get install -y libgtk2.0-dev && \
#     apt-get install -y wget bzip2 ca-certificates curl git vim tmux g++ gcc build-essential cmake checkinstall gfortran libjpeg8-dev libtiff5-dev pkg-config yasm libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine2-dev libv4l-dev qt5-default libgtk2.0-dev libtbb-dev libatlas-base-dev libfaac-dev libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev libopencore-amrnb-dev libopencore-amrwb-dev x264 v4l-utils libprotobuf-dev protobuf-compiler libgoogle-glog-dev libgflags-dev libgphoto2-dev libhdf5-dev doxygen libflann-dev libboost-all-dev proj-data libproj-dev libyaml-cpp-dev cmake-curses-gui libzmq3-dev freeglut3-dev

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 libglib2.0-0 libsm6 libxext6 libxrender1

RUN apt-get install -y ffmpeg
# RUN cd / && git clone https://github.com/pybind/pybind11 &&\
#     cd pybind11 && git checkout v2.10.0 &&\
#     mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF &&\
#     make -j6 && make install


# RUN cd / && wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz &&\
#     tar xvzf ./eigen-3.4.0.tar.gz &&\
#     cd eigen-3.4.0 &&\
#     mkdir build &&\
#     cd build &&\
#     cmake .. &&\
    # make install

SHELL ["/bin/bash", "--login", "-c"]

# RUN cd / && wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
#     /bin/bash /miniconda.sh -b -p /opt/conda &&\
#     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh &&\
#     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc &&\
#     /bin/bash -c "source ~/.bashrc" && \
#     /opt/conda/bin/conda update -n base -c defaults conda -y &&\
#     /opt/conda/bin/conda create -n my python=3.8


# ENV PATH $PATH:/opt/conda/envs/my/bin

# RUN conda init bash &&\
#     echo "conda activate my" >> ~/.bashrc &&\
#     conda activate my &&\
#     pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118 &&\
#     pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" &&\
#     pip install scipy joblib scikit-learn ruamel.yaml trimesh pyyaml opencv-python imageio open3d transformations warp-lang einops kornia pyrender


RUN unset PIP_CONSTRAINT \
    pip install --extra-index-url https://download.pytorch.org/whl/cu128 torch==2.7.1+cu128 torchaudio==2.7.1+cu128 torchvision==0.22.1+cu128 torchcodec

# install dependency build tools froum source
RUN pip install warp-lang setuptools wheel ninja
# install kaolin from source (apply PyTorch 2.6+ compat: .type() -> .scalar_type() in CUDA code)
RUN cd / && git clone --recursive https://github.com/NVIDIAGameWorks/kaolin
RUN sed -i 's/\.type()/.scalar_type()/g' /kaolin/kaolin/csrc/ops/spc/query_cuda.cu /kaolin/kaolin/csrc/ops/spc/point_utils_cuda.cu /kaolin/kaolin/csrc/render/spc/raytrace_cuda.cu 2>/dev/null || true
# Use pip install -e --no-deps to avoid pulling usd-core (not on PyPI for aarch64); install Kaolin deps manually
RUN cd /kaolin && FORCE_CUDA=1 pip install --no-deps -e .
RUN pip install pygltflib flask ipycanvas ipyevents
# install pytorch3d from source
RUN pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" --no-build-isolation
# install nvdiffrast from source
RUN pip install "git+https://github.com/NVlabs/nvdiffrast.git" --no-build-isolation


ENV OPENCV_IO_ENABLE_OPENEXR=1

RUN pip install pyyaml ruamel.yaml trimesh opencv-python==4.9.0.80 imageio transformations warp-lang einops kornia pyrender omegaconf h5py
# Official open3d has no PyPI wheel on some platforms (e.g. aarch64). Fallback to unofficial ARM wheels.
RUN pip install open3d || pip install open3d-unofficial-arm
#RUN pip install scikit-image meshcat webdataset omegaconf pypng roma seaborn opencv-contrib-python openpyxl wandb imgaug Ninja xlsxwriter timm albumentations xatlas rtree nodejs jupyterlab objaverse g4f ultralytics==8.0.120 pycocotools videoio numba h5py


ENV SHELL=/bin/bash
RUN ln -sf /bin/bash /bin/sh
